### PR TITLE
Idea for a responsive, mobile ready UKRSE website.

### PR DESCRIPTION
**Pull request by bszcz**
Created an example of a responsive design for the UKRSE website. Just an idea for now, the full site is not finished yet, everything lives isolated in the `bootstraped` directory. Check out the live version at [bszcz.org/rse.ac.uk](http://bszcz.org/rse.ac.uk)

### CODE REVIEW

**Comment by kynan** [comment]
Seems this has gone stale?

**Comment by bszcz** [comment]
@kynan Indeed it did. Seems like all the effort was wasted because someone's favourite library wasn't used although that was only revealed few months into the development. Please see the thread above for details. The original prototype is still up at [http://bszcz.org/rse.ac.uk](http://bszcz.org/rse.ac.uk).

**Comment by kynan** [comment]
@bszcz That's a shame. I wonder if the effort could still be rescued. You could have individual sections in markdown source and `{% include <section>.md %}`. The problem is that the markdown will be translated to fairly standard html and you can't easily add classes/attributes to elements.

**Comment by jamespjh** [comment]
We do need a responsive design soon, and @bszcz 's work was great, but there was, ahem, an unfortunate miscommunication about wanting to persist with the github pages model based on markdown generating HTML. (Jekyll is the engine behind github pages.) Apologies to Bartosz. Closing this...

**Pull request closed without merging**
